env: TRAVIS_DEBIAN_TARGET_DIR=../result TRAVIS_DEBIAN_DISTRIBUTION=jessie

sudo: required

services:
 - docker

script:
 - wget -O- http://travis.debian.net/script.sh | sh -

deploy:
  provider: releases
  api_key: ${GITHUB_API_KEY}
  file_glob: true
  file: "../result/*"
  skip_cleanup: true
  on:
    tags: true
